### ISSUE TITLE
Add coverage reports to jest

### ISSUE THREAD

**Issue by dangoslen** [dangoslen/constable-github-action#18]
Use the `--coverage` option in jest to collect and report code coverage

Consider adding a badge to our README

**Comment by bmind12** [comment]
Hi @dangoslen, for the badge, what would you like to use? There are options like [a package](https://www.npmjs.com/package/jest-coverage-badges) or [a service](https://github.com/dwyl/learn-istanbul#tracking-coverage-as-a-service)

**Comment by dangoslen** [comment]
👋  @bmind12 

I think just using a package is the best option for now. Just wanting to get something started.
